# Generated by Django 4.0.5 on 2022-06-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=32)),
                ('image', models.URLField(max_length=500)),
                ('owner', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=50)),
                ('thoughts', models.CharField(max_length=50)),
            ],
        ),
    ]
